services:
  web01:
   build:
    context: ./web01
    dockerfile: Dockerfile
   image: web01
   container_name: web01
   networks:
    - asa-network
  
  web02:
   build:
    context: ./web02
    dockerfile: Dockerfile
   image: web02
   container_name: web02
   networks:
    - asa-network

  dns:
   build:
    context: ./dns
    dockerfile: Dockerfile
   image: dns
   container_name: dns
   hostname: ifrn.asa.br
   restart: always
   tty: true
   ports:
    - "53:53/tcp"
    - "53:53/udp"
   networks:
    - asa-network

  proxy:
   build:
    context: ./proxy
    dockerfile: Dockerfile
   image: proxy
   container_name: proxy
   ports:
    - "80:80"
   depends_on:
    - web
    
   networks:
    - asa-network
  
  wordpress:
    image: wordpress
    restart: always
   
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
  
#Docker Networks
networks:
  asa-network:
   driver: bridge

volumes:
  wordpress:
  db: